<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <AssemblyName>totem</AssemblyName>
    <RootNamespace>totem</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <StartupObject>totem.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="ILRepack" Version="2.0.44" GeneratePathProperty="true" ExcludeAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
    <Resource Include="font\*.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Security" />
  </ItemGroup>
  <Target Name="SingleFile" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <PropertyGroup>
      <SingleFileDir>$(MSBuildProjectDirectory)\publish</SingleFileDir>
    </PropertyGroup>
    <ItemGroup>
      <MergeInput Include="$(TargetDir)$(TargetFileName)" />
      <MergeInput Include="$(TargetDir)*.dll" />
    </ItemGroup>
    <MakeDir Directories="$(SingleFileDir)" />
    <Exec Command="&quot;$(PkgILRepack)\tools\ILRepack.exe&quot; /out:&quot;$(SingleFileDir)\$(TargetFileName)&quot; /target:winexe /targetplatform:v4 @(MergeInput->'&quot;%(FullPath)&quot;', ' ')" />
    <Message Importance="high" Text="Single file: $(SingleFileDir)\$(TargetFileName)" />
  </Target>
</Project>
